export const USERNAME_CHANGE = 'USERNAME_CHANGE';
export const UPDATE_CARDS_IN_POT = 'UPDATE_CARDS_IN_POT';
export const UPDATE_PLAYER_HAND = 'UPDATE_PLAYER_HAND';
export const ADD_CARD_TO_SELECTED = 'ADD_CARD_TO_SELECTED';
export const CLEAR_CARDS_FROM_SELECTION = 'CLEAR_CARDS_FROM_SELECTION';
